### ISSUE TITLE
None

### ISSUE THREAD

**Issue by DBook111** [ShellRedia/SAM-OCTA#4]
None

**Comment by DBook111** [comment]
也就是说在测试阶段，prompt encoder的输入是什么呢？是用torch.empty做空张量传进去吗？

**Comment by ShellRedia** [comment]
这个我其实还是把标签引用进来生成提示点的。当然我也考虑了没有提示信息的情况，那就是对常数进行编码[(-100, -100, 0)]这种处理方式，类似于您说的用torch.empty做空张量传进去的方式。
